Repository thoth-station/license-solver, pull requests merged in 2022-03, with the labels that each got.

#39 Remove template bits
  template/__init__.py
  template/version.py
Labels: size/S, approved

#43 Update README.rst
  README.rst
Labels: size/L, approved

#44 Change list of licenses to dictionary + test fix
  tests/comparator_test.py
  tests/output_creator_test.py
  tests/package_test.py
  tests/solver_test.py
  tests/test_files/solver/test_solver_files/license-no_version-1.json
  tests/test_files/solver/test_solver_files/license-no_version-2.json
  tests/test_files/solver/test_solver_files/license-norm-1.json
  tests/test_files/solver/test_solver_files/license-norm-2.json
  tests/test_files/solver/test_solver_files/license-norm-short-no_version-1.json
  tests/test_files/solver/test_solver_files/license-norm-short-no_version-2.json
  tests/test_files/solver/test_solver_files/license-norm-short-no_version-3.json
  tests/test_files/solver/test_solver_files/license-norm-version.json
  tests/test_files/solver/test_solver_files/license-not-norm-1.json
  tests/test_files/solver/test_solver_files/license-not-norm-2.json
  tests/test_files/solver/test_solver_files/license-unknown-1.json
  tests/test_files/solver/test_solver_files/license-unknown-2.json
  tests/test_files/solver/test_solver_files/license-unknown-3.json
  tests/test_files/solver/test_solver_files/license-unknown-4.json
  thoth/license_solver/comparator.py
  thoth/license_solver/licenses.py
  thoth/license_solver/package.py
Labels: size/L, approved

#56 update pyproject.toml
  pyproject.toml
Labels: approved, size/XS
